# Generated by Django 5.0.2 on 2024-02-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20201209_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                default="images/default_user_image.jpg", upload_to="images"
            ),
        ),
    ]
